### ISSUE TITLE
Не компилится

### ISSUE THREAD

**Issue by Nixend-creator** [serfreeman1337/aes#1]
Привет.
aes_main.sma компилится
дальше вот что
http://prntscr.com/bd1cpp

http://prntscr.com/bd1d08

Инклуду обновлял

**Comment by serfreeman1337** [comment]
Исправлю перед релизом (ахахах).
Пока можешь в начало файла aes_main.inс добавить:

```
#define MAX_NAME_LENGTH 32
#define MAX_PLAYERS 32
```

**Comment by Nixend-creator** [comment]
http://prntscr.com/bd4wew
еще бага
