### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by Nixend-creator** [serfreeman1337/aes#2]
короче баг заключается в том что опыт в цифрах пишет типа так
12354689988742565/1412556665666554545
как пофиксить?

**Comment by serfreeman1337** [comment]
Забыл обновить словари :)
В aes.txt нужно заменить %d на %.0f или на %.2f.

**Comment by Nixend-creator** [comment]
А по точнее? на что менять?) хД)

**Comment by Nixend-creator** [comment]
короче на %.2f
VALUES('%s','%s','%.2f','%d','%s');",

**Comment by Nixend-creator** [comment]
Короче пишет 0.00/20.00 и не записывается экспа.

**Comment by serfreeman1337** [comment]
Только не говори, что ты менял в исходнике...
В словаре aes.txt нужно менять и больше нигде.

За начисления опыта отвечает плагин aes_exp_cstrike.sma, он должен быть включен.
Проверь не стоит ли квар aes_track_pause в 1.
Проверь сохранение опыта с помощью aes_exp_editior.sma, команда aes_exp_menu.

Если используешь CSstatsXSQL в качестве замены модуля, то тебе нужно включить форварды, читай инструкцию.

**Comment by Nixend-creator** [comment]
[ 49] Advanced Experience Sy  0.5 Vega    serfreeman1337    aes_main.amxx    running  
          [ 50] AES: Cstrike Addon      0.5 Vega    serfreeman1337    aes_exp_cstrike  running  
          [ 51] AES: Informer           0.5 Vega    serfreeman1337    aes_informer.am  running  
          [ 52] AES: Bonus System       0.5 Vega    serfreeman1337    aes_bonus_syste  running  
          [ 53] AES: Bonus CSTRIKE      0.4         serfreeman1337    aes_bonus_cstri  running  
          [ 54] AES: Status Info        0.1         serfreeman1337    aes_status_info  running  
aes_track_pause = 0
Без замены модуля.

**Comment by Nixend-creator** [comment]
команда aes_exp_menu добавляет опыт
