### ISSUE TITLE
Ошибка бд

### ISSUE THREAD

**Issue by Nixend-creator** [serfreeman1337/aes#4]
Не читает с конфига данные
L 06/12/2016 - 06:16:10: [aes_main.amxx] SQL connection failed
L 06/12/2016 - 06:16:10: [aes_main.amxx] [ 1045 ] Access denied for user 'admin_stats'@'179.60.148.36' (using password: NO)

Пришлось прописать в исходник.

**Comment by serfreeman1337** [comment]
В **aes.cfg** название квара **aes_sql_password**, в то время как плагин использует **aes_sql_pass**.
