### ISSUE TITLE
Баг с бонусами

### ISSUE THREAD

**Issue by Nixend-creator** [serfreeman1337/aes#5]
С бонусными очками беда
Когда за них что то берешь, пишет
https://pp.vk.me/c626129/v626129126/12190/9NoX4v_fQ3M.jpg

**Comment by serfreeman1337** [comment]
Кол-во требуемых бонус очков настраивается в [configs/aes/bonus.ini](https://github.com/serfreeman1337/aes/blob/dev/configs/aes/bonus.ini#L101) через переменную **points**.

**Comment by Nixend-creator** [comment]
Пример можно?

**Comment by Nixend-creator** [comment]
Разобрался.
