### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Nixend-creator** [serfreeman1337/aes#6]
Чет жалуются не работает команда /anew из-за чего она не может работать?

**Comment by serfreeman1337** [comment]
А сам проверял? ХД
1ое правило админа: никогда не верь игрокам твоего сервера.

**Comment by Nixend-creator** [comment]
Проверил, не пашет при таких настройках
[items]

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_M4A1
function = pointBonus_GiveM4a1
points = 1
round = 2

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_AK47
function = pointBonus_GiveAk47
points = 1
round = 2

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_AWP
function = pointBonus_GiveAWP
points = 1
round = 2

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_10000M
function = pointBonus_Give10000M
points = 1
round = 2

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_200HP
function = pointBonus_Set200HP
points = 2
round = 2

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_MEGAGRENADE
function = pointBonus_GiveMegaGrenade
points = 2
round = 2

<call>
plugin = aes_bonus_cstrike.amxx
name = LANG_AES_BONUS_MEGADEAGLE
function = pointBonus_GiveMegaDeagle
points = 2
round = 2

**Comment by serfreeman1337** [comment]
А если без round?
Чтобы работала настройка _round_, квар **aes_bonus_spawn** должен быть установлен в **2**.

**Comment by Nixend-creator** [comment]
Как сделать что бы один раз за раунд бралось?
